---
title: "Reproducible Research: Peer Assessment 1"
author: "Pablo Panos"
output: 
  html_document:
    keep_md: true
# Peer Assesment 1 
## Pablo Paños Lajusticia
---
Loading Data and processing it

```{r readingData}
library(dplyr)
library(ggplot2)
mydf<- tbl_df(read.csv("./activity.csv",header = TRUE))
mydf[,"date"]<- as.Date(as.character(mydf$date),"%F")

```

Plotting a Histogram Total number of steps taken each day
```{r plotting Histogram}
mydfg<-group_by(mydf,date)
stepsbyday<-summarise(mydfg,sum(steps,na.rm = TRUE))
hist(stepsbyday$`sum(steps, na.rm = TRUE)`,main = "Total number of steps taken each day",xlab = "Number of Steps")
```

Calculating the Mean and Meadian
```{r}
summarise_each(group_by(mydf,date),funs(mean,median),steps)
```
Plotting Time Series
```{r}
intervaldf<-summarise(group_by(mydf,interval),mean(steps,na.rm = TRUE))
plot(intervaldf$interval,intervaldf$`mean(steps, na.rm = TRUE)`,type="l",xlab = "Interval",ylab = "Mean" )
```

Max 5-minute interval on average across all the days in the dataset, contains the maximum number of steps
```{r}
intersumdf<-summarise(group_by(mydf,interval),sum=sum(steps,na.rm = TRUE))
filter(intersumdf,sum == max(intersumdf$sum))
```
